### ISSUE TITLE
第一次使用CoolQ，能否写一个readme，方便快速上手

### ISSUE THREAD

**Issue by huangtao00** [yukixz/cqsocketapi#1]
python+socketapi使用CoolQ的想法非常不错，对于喜欢开源的朋友真是太好了！
能否写一个readme,这样可以快速上手使用CoolQ,而不用把时间放在CoolQ的配置上
方便的话，如果可以建一个群就更好了，大家有问题可以在群里交流！CoolQ的稳定性非常好，加上pyhton的快速开发，这个项目实用性还是非常强的！ CQBot这个demo项目使用了python3.5，表示还在用python2.7！

**Comment by yukixz** [comment]
酷Q的使用教程我不管诶。去酷Q论坛翻翻吧、那里资料很多…
建群考虑一下😝

On Wednesday, 29 June 2016, huangtao00 notifications@github.com wrote:

> python+socketapi使用CoolQ的想法非常不错，对于喜欢开源的朋友真是太好了！
> 能否写一个readme,这样可以快速上手使用CoolQ,而不用把时间放在CoolQ的配置上
> 方便的话，如果可以建一个群就更好了，大家有问题可以在群里交流！CoolQ的稳定性非常好，加上pyhton的快速开发，这个项目实用性还是非常强的！
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/yukixz/cqsocketapi/issues/1, or mute the thread
> https://github.com/notifications/unsubscribe/ADLuwQulB-HXP4yUKsqeb9Uy4uYda9eEks5qQd-TgaJpZM4JAuih
> .

## 

_Dazzy Ding_
Email: h@dazzyd.org
