### ISSUE TITLE
新版的酷Q udp客户端好像没法接受消息

### ISSUE THREAD

**Issue by hsxin** [yukixz/cqsocketapi#12]
新版的酷Q udp客户端好像没法接受消息，能否改成tcp？

**Comment by yukixz** [comment]
😱

**Comment by hsxin** [comment]
我用的是java写的客户端，使用UDP调用的接受，发消息没得问题，就是没法接受到消息

**Comment by hsxin** [comment]
void APIClient::send(const char *buffer, const int len)
{
	time_t timeout = time(0) - CLIENT_TIMEOUT;
	char log[1024];

	for (int i = 0; i < CLIENT_SIZE; i++) {
		if (clients[i].hello < 0) {
			continue;
		}
		if (clients[i].hello < timeout) {
			clients[i].hello = -1;
			sprintf_s(log, "Client removed: %d.", clients[i].port);
			CQ_addLog(appAuthCode, CQLOG_INFO, "APIClient", log);
			continue;
		}
		sendto(sock, buffer, len, 0, (sockaddr *)&clients[i].info, sizeof(clients[i].info));
	}
}
:scream: 如果可以的话 复写一个tcp，一个写文件的，一个http回调的接口 。

**Comment by yukixz** [comment]
tcp server 比 udp server 难写多了😞

**Comment by yukixz** [comment]
你发 clienthello 了吗👀

**Comment by yukixz** [comment]
不对呀、我检查了一下我的 python 实现是正常的。
你确认一下你的实现有没有问题👀

**Comment by hsxin** [comment]
我的实现貌似没得问题，发消息正常 ，正在研究你的python robot.

**Comment by hsxin** [comment]
![image](https://cloud.githubusercontent.com/assets/3447075/20469652/709cad9e-afdc-11e6-8d0e-e395a6c58a20.png)

**Comment by yukixz** [comment]
有 add 消息就会正常发送了的👀

**Comment by hsxin** [comment]
![image](https://cloud.githubusercontent.com/assets/3447075/20469729/0ae0c214-afdd-11e6-9442-48ddc1086254.png)
没看到发送消息

**Comment by yukixz** [comment]
发送不会有 log 的呀… 不然 log 会炸的

**Comment by yukixz** [comment]
😞总之我这边没有问题…
你的问题是 酷q发出到java应用这段路走不通

**Comment by hsxin** [comment]
![image](https://cloud.githubusercontent.com/assets/3447075/20469788/843031ea-afdd-11e6-8067-a70148252646.png)

**Comment by hsxin** [comment]
估计是udp不行哈

**Comment by yukixz** [comment]
😔我这边正常就是了。我看不到你的应用也没法猜出问题在哪。
