### ISSUE TITLE
请问这个插件对酷q本身所有功能的适配性如何？

### ISSUE THREAD

**Issue by needhourger** [yukixz/cqsocketapi#20]
除了最基础的消息收发之外，对加好友消息，群员管理这方面的酷q功能支持如何？
没有在readme中看到相关方面的资料，有点小疑问

**Comment by yukixz** [comment]
不支持。
这个项目已经不再维护了，建议寻找代替方案。

**Comment by needhourger** [comment]
好的了解了，谢谢。
